# Exported from Render on 2025-04-21T08:44:03Z
services:
- type: web
  name: n8n
  runtime: image
  image:
    url: docker.n8n.io/n8nio/n8n:latest
  plan: free
  envVars:
  - key: N8N_EDITOR_BASE_URL
    sync: false
  - key: WEBHOOK_URL
    sync: false
  - key: N8N_PROTOCOL
    sync: false
  - key: N8N_PORT
    sync: false
  - key: N8N_HOST
    sync: false
  region: oregon
version: "1"
